import { cva } from 'class-variance-authority'

export const badgeVariants = cva(
  [
    // Layout & Structure
    'inline-flex',
    'items-center',
    'justify-center',
    'w-fit',
    'shrink-0',
    'gap-1',
    'whitespace-nowrap',
    'overflow-hidden',

    // Visual Design
    'rounded-md',
    'border',
    'border-transparent',
    'font-medium',

    // Icons
    '[&>svg]:pointer-events-none',

    // Interactive Cursors
    '[a&]:cursor-pointer',
    '[button&]:cursor-pointer',

    // Focus States for Interactive Elements
    '[a&]:focus-visible:outline-none',
    '[a&]:focus-visible:ring-2',
    '[a&]:focus-visible:ring-ring',
    '[a&]:focus-visible:ring-offset-2',
    '[button&]:focus-visible:outline-none',
    '[button&]:focus-visible:ring-2',
    '[button&]:focus-visible:ring-ring',
    '[button&]:focus-visible:ring-offset-2',

    // Disabled States for Buttons
    '[button&]:disabled:cursor-not-allowed',
    '[button&]:disabled:opacity-50',
    '[button&]:disabled:grayscale',

    // Accessibility & States
    'aria-invalid:ring-destructive/20',
    'dark:aria-invalid:ring-destructive/40',
    'aria-invalid:border-destructive',

    // Transitions
    'transition-[color,box-shadow]',
  ],
  {
    variants: {
      color: {
        // Bright Colors - Standard Pattern
        blue: [
          'bg-blue-100',
          'text-blue-900',
          'dark:bg-blue-950',
          'dark:text-blue-100',
          '[a&]:hover:bg-blue-200',
          'dark:[a&]:hover:bg-blue-900',
          '[button&]:hover:bg-blue-200',
          'dark:[button&]:hover:bg-blue-900',
          '[button&]:disabled:hover:bg-blue-100',
          'dark:[button&]:disabled:hover:bg-blue-950',
        ],
        red: [
          'bg-red-100',
          'text-red-900',
          'dark:bg-red-950',
          'dark:text-red-100',
          '[a&]:hover:bg-red-200',
          'dark:[a&]:hover:bg-red-900',
          '[button&]:hover:bg-red-200',
          'dark:[button&]:hover:bg-red-900',
          '[button&]:disabled:hover:bg-red-100',
          'dark:[button&]:disabled:hover:bg-red-950',
        ],
        green: [
          'bg-green-100',
          'text-green-900',
          'dark:bg-green-950',
          'dark:text-green-100',
          '[a&]:hover:bg-green-200',
          'dark:[a&]:hover:bg-green-900',
          '[button&]:hover:bg-green-200',
          'dark:[button&]:hover:bg-green-900',
          '[button&]:disabled:hover:bg-green-100',
          'dark:[button&]:disabled:hover:bg-green-950',
        ],
        yellow: [
          'bg-yellow-100',
          'text-yellow-900',
          'dark:bg-yellow-950',
          'dark:text-yellow-100',
          '[a&]:hover:bg-yellow-200',
          'dark:[a&]:hover:bg-yellow-900',
          '[button&]:hover:bg-yellow-200',
          'dark:[button&]:hover:bg-yellow-900',
          '[button&]:disabled:hover:bg-yellow-100',
          'dark:[button&]:disabled:hover:bg-yellow-950',
        ],
        purple: [
          'bg-purple-100',
          'text-purple-900',
          'dark:bg-purple-950',
          'dark:text-purple-100',
          '[a&]:hover:bg-purple-200',
          'dark:[a&]:hover:bg-purple-900',
          '[button&]:hover:bg-purple-200',
          'dark:[button&]:hover:bg-purple-900',
          '[button&]:disabled:hover:bg-purple-100',
          'dark:[button&]:disabled:hover:bg-purple-950',
        ],
        orange: [
          'bg-orange-100',
          'text-orange-900',
          'dark:bg-orange-950',
          'dark:text-orange-100',
          '[a&]:hover:bg-orange-200',
          'dark:[a&]:hover:bg-orange-900',
          '[button&]:hover:bg-orange-200',
          'dark:[button&]:hover:bg-orange-900',
          '[button&]:disabled:hover:bg-orange-100',
          'dark:[button&]:disabled:hover:bg-orange-950',
        ],
        pink: [
          'bg-pink-100',
          'text-pink-900',
          'dark:bg-pink-950',
          'dark:text-pink-100',
          '[a&]:hover:bg-pink-200',
          'dark:[a&]:hover:bg-pink-900',
          '[button&]:hover:bg-pink-200',
          'dark:[button&]:hover:bg-pink-900',
          '[button&]:disabled:hover:bg-pink-100',
          'dark:[button&]:disabled:hover:bg-pink-950',
        ],
        emerald: [
          'bg-emerald-100',
          'text-emerald-900',
          'dark:bg-emerald-950',
          'dark:text-emerald-100',
          '[a&]:hover:bg-emerald-200',
          'dark:[a&]:hover:bg-emerald-900',
          '[button&]:hover:bg-emerald-200',
          'dark:[button&]:hover:bg-emerald-900',
          '[button&]:disabled:hover:bg-emerald-100',
          'dark:[button&]:disabled:hover:bg-emerald-950',
        ],
        teal: [
          'bg-teal-100',
          'text-teal-900',
          'dark:bg-teal-950',
          'dark:text-teal-100',
          '[a&]:hover:bg-teal-200',
          'dark:[a&]:hover:bg-teal-900',
          '[button&]:hover:bg-teal-200',
          'dark:[button&]:hover:bg-teal-900',
          '[button&]:disabled:hover:bg-teal-100',
          'dark:[button&]:disabled:hover:bg-teal-950',
        ],
        cyan: [
          'bg-cyan-100',
          'text-cyan-900',
          'dark:bg-cyan-950',
          'dark:text-cyan-100',
          '[a&]:hover:bg-cyan-200',
          'dark:[a&]:hover:bg-cyan-900',
          '[button&]:hover:bg-cyan-200',
          'dark:[button&]:hover:bg-cyan-900',
          '[button&]:disabled:hover:bg-cyan-100',
          'dark:[button&]:disabled:hover:bg-cyan-950',
        ],
        sky: [
          'bg-sky-100',
          'text-sky-900',
          'dark:bg-sky-950',
          'dark:text-sky-100',
          '[a&]:hover:bg-sky-200',
          'dark:[a&]:hover:bg-sky-900',
          '[button&]:hover:bg-sky-200',
          'dark:[button&]:hover:bg-sky-900',
          '[button&]:disabled:hover:bg-sky-100',
          'dark:[button&]:disabled:hover:bg-sky-950',
        ],
        indigo: [
          'bg-indigo-100',
          'text-indigo-900',
          'dark:bg-indigo-950',
          'dark:text-indigo-100',
          '[a&]:hover:bg-indigo-200',
          'dark:[a&]:hover:bg-indigo-900',
          '[button&]:hover:bg-indigo-200',
          'dark:[button&]:hover:bg-indigo-900',
          '[button&]:disabled:hover:bg-indigo-100',
          'dark:[button&]:disabled:hover:bg-indigo-950',
        ],
        violet: [
          'bg-violet-100',
          'text-violet-900',
          'dark:bg-violet-950',
          'dark:text-violet-100',
          '[a&]:hover:bg-violet-200',
          'dark:[a&]:hover:bg-violet-900',
          '[button&]:hover:bg-violet-200',
          'dark:[button&]:hover:bg-violet-900',
          '[button&]:disabled:hover:bg-violet-100',
          'dark:[button&]:disabled:hover:bg-violet-950',
        ],
        fuchsia: [
          'bg-fuchsia-100',
          'text-fuchsia-900',
          'dark:bg-fuchsia-950',
          'dark:text-fuchsia-100',
          '[a&]:hover:bg-fuchsia-200',
          'dark:[a&]:hover:bg-fuchsia-900',
          '[button&]:hover:bg-fuchsia-200',
          'dark:[button&]:hover:bg-fuchsia-900',
          '[button&]:disabled:hover:bg-fuchsia-100',
          'dark:[button&]:disabled:hover:bg-fuchsia-950',
        ],
        rose: [
          'bg-rose-100',
          'text-rose-900',
          'dark:bg-rose-950',
          'dark:text-rose-100',
          '[a&]:hover:bg-rose-200',
          'dark:[a&]:hover:bg-rose-900',
          '[button&]:hover:bg-rose-200',
          'dark:[button&]:hover:bg-rose-900',
          '[button&]:disabled:hover:bg-rose-100',
          'dark:[button&]:disabled:hover:bg-rose-950',
        ],
        amber: [
          'bg-amber-100',
          'text-amber-900',
          'dark:bg-amber-950',
          'dark:text-amber-100',
          '[a&]:hover:bg-amber-200',
          'dark:[a&]:hover:bg-amber-900',
          '[button&]:hover:bg-amber-200',
          'dark:[button&]:hover:bg-amber-900',
          '[button&]:disabled:hover:bg-amber-100',
          'dark:[button&]:disabled:hover:bg-amber-950',
        ],
        lime: [
          'bg-lime-100',
          'text-lime-900',
          'dark:bg-lime-950',
          'dark:text-lime-100',
          '[a&]:hover:bg-lime-200',
          'dark:[a&]:hover:bg-lime-900',
          '[button&]:hover:bg-lime-200',
          'dark:[button&]:hover:bg-lime-900',
          '[button&]:disabled:hover:bg-lime-100',
          'dark:[button&]:disabled:hover:bg-lime-950',
        ],

        // Neutral Colors - Special Pattern (800/700 instead of 950/900)
        zinc: [
          'bg-zinc-100',
          'text-zinc-900',
          'dark:bg-zinc-800',
          'dark:text-zinc-100',
          '[a&]:hover:bg-zinc-200',
          'dark:[a&]:hover:bg-zinc-700',
          '[button&]:hover:bg-zinc-200',
          'dark:[button&]:hover:bg-zinc-700',
          '[button&]:disabled:hover:bg-zinc-100',
          'dark:[button&]:disabled:hover:bg-zinc-800',
        ],
        slate: [
          'bg-slate-100',
          'text-slate-900',
          'dark:bg-slate-800',
          'dark:text-slate-100',
          '[a&]:hover:bg-slate-200',
          'dark:[a&]:hover:bg-slate-700',
          '[button&]:hover:bg-slate-200',
          'dark:[button&]:hover:bg-slate-700',
          '[button&]:disabled:hover:bg-slate-100',
          'dark:[button&]:disabled:hover:bg-slate-800',
        ],
        gray: [
          'bg-gray-100',
          'text-gray-900',
          'dark:bg-gray-800',
          'dark:text-gray-100',
          '[a&]:hover:bg-gray-200',
          'dark:[a&]:hover:bg-gray-700',
          '[button&]:hover:bg-gray-200',
          'dark:[button&]:hover:bg-gray-700',
          '[button&]:disabled:hover:bg-gray-100',
          'dark:[button&]:disabled:hover:bg-gray-800',
        ],
        neutral: [
          'bg-neutral-100',
          'text-neutral-900',
          'dark:bg-neutral-800',
          'dark:text-neutral-100',
          '[a&]:hover:bg-neutral-200',
          'dark:[a&]:hover:bg-neutral-700',
          '[button&]:hover:bg-neutral-200',
          'dark:[button&]:hover:bg-neutral-700',
          '[button&]:disabled:hover:bg-neutral-100',
          'dark:[button&]:disabled:hover:bg-neutral-800',
        ],
        stone: [
          'bg-stone-100',
          'text-stone-900',
          'dark:bg-stone-800',
          'dark:text-stone-100',
          '[a&]:hover:bg-stone-200',
          'dark:[a&]:hover:bg-stone-700',
          '[button&]:hover:bg-stone-200',
          'dark:[button&]:hover:bg-stone-700',
          '[button&]:disabled:hover:bg-stone-100',
          'dark:[button&]:disabled:hover:bg-stone-800',
        ],
      },
      size: {
        sm: ['px-1.5', 'py-0.5', 'text-xs', '[&>svg]:size-3'],
        md: ['px-2', 'py-1', 'text-sm', '[&>svg]:size-4'],
        lg: ['px-2.5', 'py-1.5', 'text-base', '[&>svg]:size-5'],
      },
    },
    defaultVariants: {
      color: 'zinc',
      size: 'md',
    },
  },
)
